// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv"
import { defineConfig } from "prisma/config"

config() // 👈 explicitly load .env

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is missing")
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL
  }
})
